filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /usr/share/filebeat/config/nginx/access.log

processors:
  - drop_fields:
      fields: ["beat", "input_type", "prospector", "input", "host", "agent"]

output.logstash: 
  hosts: ["logstash:5044"]