#version: '3'
services:
  # Elasticsearch Docker Images: https://www.docker.elastic.co/
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
    container_name: elasticsearch-rvs
    environment:
      - cluster.name=renev-vs-cluster
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - ./configs/elasticsearch/config.yml:/user/share/elasticsearch/config/elasticsearch.yml
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    container_name: kibana-rvs
    image: docker.elastic.co/kibana/kibana:7.16.1
    volumes:
      - ./configs/kibana/config.yml:/usr/share/kibana/config/kibana.yml
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  logstash:
    container_name: logstash-rvs
    image: docker.elastic.co/logstash/logstash:7.16.1
    environment:
      XPACK_MONITORING_ENABLED: "false"
      ES_HOST: "elasticsearch:9200"  
    ports:
       - "5044:5044"
#       - "5044:5044/udp"
    volumes:
      - ./configs/logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./configs/logstash/pipelines:/usr/share/logstash/config/pipelines
#     - ./nginxlogs:/usr/share/logstash/config/nginx
    depends_on:
      - elasticsearch

  beats:
    image: docker.elastic.co/beats/filebeat:7.16.1
    command: --strict.perms=false
    user: root
    volumes:
      - ./configs/filebeat/config.yml:/usr/share/filebeat/filebeat.yml
      - ./nginxlogs:/usr/share/filebeat/config/nginx
    depends_on:
      - logstash
      - elasticsearch
      - kibana

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginxlogs:/var/log/nginx

volumes:
  elasticsearch-data:
    driver: local


# echo '192.168.0.1 internal 500' | nc -u localhost 5044

# curl http://localhost:9200/_cluster/health?pretty
# curl http://localhost:9200/_aliases
# curl http://localhost:9200//_cat/indices
# http://localhost:5601/app/dev_tools#/console



#      - /projects/test/filebeat.yml:/usr/share/filebeat/filebeat.yml
#      - /var/lib/docker:/var/lib/docker:ro
#      - /var/run/docker.sock:/var/run/docker.sock