version: '3.7'
services:
  # Elasticsearch Docker Images: https://www.docker.elastic.co/
  logstash:
    container_name: logstash_renev_vs
    image: docker.elastic.co/logstash/logstash:7.17.9
    environment:
      XPACK_MONITORING_ENABLED: "false"
    networks:
      - my
    ports:
      - 5044:5044
    volumes:
      - ./config/logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - ./config/logstash/pipelines:/usr/share/logstash/config/pipelines:ro
      - ./nginxlogs:/usr/share/logstash/input
    depends_on:
      - elasticsearch

  elasticsearch:
    container_name: elasticsearch_renev_vs
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    environment:
      - cluster.name=renev_vs-cluster
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - my
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    container_name: kibana_renev_vs
    image: docker.elastic.co/kibana/kibana:7.17.9
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - my
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - my
    volumes:
      - ./nginxlogs:/var/log/nginx 
    restart: always

networks:
  my:
    driver: bridge

volumes:
  elasticsearch-data:
    driver: local